### ISSUE TITLE
Heart?

### ISSUE THREAD

**Issue by aliosmanyuksel** [cjhbtn/periscopr-api#1]
Can you add heart function? Is it possible?

Regards.

@cjhbtn

**Comment by cjhbtn** [comment]
Thanks for the request.

It certainly looks possible to add this in to the library, although further research would be needed.

For example, live heart giving (as seen in broadcasts) is likely handled by the PubNub presence and chat system, which I hope to document more next week.

There is also **n_hearts** as a parameter of the [/stopWatching](https://github.com/cjhbtn/periscopr-api/wiki/Periscope_API_Endpoints_StopWatching) endpoint.

I'd need to see if it's possible to send the heart details in a /stopWatching request, without the associated PubNub entries, to know whether it can be done completely in this library.

**Comment by aliosmanyuksel** [comment]
Okay, thank you so much.

So can you give me Periscope Consumer Key and Secret? I wanna develop to web site.

My mail: info@aliosmanyuksel.com.tr

Regards.

@cjhbtn

**Comment by cjhbtn** [comment]
Sorry, but I'm not currently disclosing the Consumer Key and Secret.

I have some commercial ideas planned, and don't want to cannibalise the market before I've had a chance to get them out.. :)

If you have a specific project/idea in mind, mail me chris@periscopr.uk with details. If it doesn't match with my idea, I'll give you access to [Tokenr](https://tokenr.periscopr.uk) for a specific Twitter account so you can develop further.

**Comment by aliosmanyuksel** [comment]
I send a mail... :)

**Comment by cjhbtn** [comment]
Hearts can be sent through PingWatching, StopWatching and EndReplayViewed.

Tokenr is also now publicly available.
