### ISSUE TITLE
Fatal error: Class 'Cjhbtn\Periscopr\Api\Client' not found in

### ISSUE THREAD

**Issue by dmrnm** [cjhbtn/periscopr-api#2]
hi i'm trying this api but after installation with composer,
 in the example i get an error, how can i solve it?

Fatal error: Class 'Cjhbtn\Periscopr\Api\Client' not found in C:\xampp\htdocs\periscope\test\index.php on line 7

<?php

    require_once __DIR__ . '/vendor/autoload.php';

    /* Create a new instance of the API Client */
    $periscopeClient = new Cjhbtn\Periscopr\Api\Client();

    /* Prepare a LoginTwitter request with our OAuth credentials */
    $loginRequest = new Cjhbtn\Periscopr\Api\Requests\LoginTwitter([
        'session_key'    => 'OAUTH_TOKEN GOES HERE',
        'session_secret' => 'OAUTH_TOKEN_SECRET GOES HERE'
    ]);

    /* Execute the request against the API */
    $loginResponse = $periscopeClient->execute($loginRequest);

    /* Check to see if the request was successful */
    if ($loginResponse->getStatusCode() !== 200) {
        die("Unable to login to Periscope API");
    }

    /* Set our authentication cookie for all future requests */
    $periscopeClient->setCookie($loginResponse->cookie);

    /* Prepare a new GetFeedLive request */
    $liveBroadcastsRequest = new Cjhbtn\Periscopr\Api\Requests\LiveBroadcastFeed();

    /* Execute the request against the API */
    $liveBroadcastsResponse = $periscopeClient->execute($liveBroadcastsRequest);

    /* Check to see if the request was successful */
    if ($liveBroadcastsResponse->getStatusCode() !== 200) {
        die("Unable to fetch Live Broadcasts from Periscope API");
    }

    /* Output the contents of the results */
    echo json_encode($liveBroadcastsResponse->results[0]);

?>

**Comment by cjhbtn** [comment]
Hi,

Is your index.php file on the same folder level as the 'vendor' directory? If not, you'll need to either adjust the require_once line to match the real location of 'vendor', or move index.php.

If you still encounter problems, try re-dumping the autoloader by running the following:

      composer dump-autoload

Let me know if you still have any issues.

Regards,
Chris

**Comment by cjhbtn** [comment]
Actually, it's more likely to be that the composer install pulled the wrong version - the example is for the dev-master branch rather than 1.x-dev branch or 1.0-alpha tag.

I'll update the install instructions in dev-master to ensure it pulls in the correct version - thanks for the report!

Regards,
Chris
