### ISSUE TITLE
required user_id error 

### ISSUE THREAD

**Issue by Tartoob** [cjhbtn/periscopr-api#3]
<per>PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Missing required parameter: user_id' in /var/www/vendor/cjhbtn/periscopr-api/src/Requests/LoginTwitter.php:24
Stack trace:
#0 /var/www/p.php(13): Cjhbtn\Periscopr\Api\Requests\LoginTwitter->__construct(Array)
#1 {main}
  thrown in /var/www/vendor/cjhbtn/periscopr-api/src/Requests/LoginTwitter.php on line 24
</per>

I added user_id on $loginRequest also I create new application on twitter API and I add Consumer Key (API Key) and Consumer Secret (API Secret), It shows me Unable to login to Periscope API

Any ideas please

**Comment by Tartoob** [comment]
By the way I create oauth_token and I test it and it works
https://api.twitter.com/oauth/authenticate?oauth_token=YmW4AAAAAAAAg4qoAAABTvGLr1U

but Unfortunately still have the same error with 401 getStatusCode()

**Comment by cjhbtn** [comment]
Hi,

Thanks for the report about the user_id error. This was an error with README.md which didn't show 'user_id' as a required parameter for the LoginTwitter request. This is now fixed.

WRT the authentication, you cannot use your own Twitter Consumer Key and Secret, you need to generate an OAuth Token and Secret using the Periscope Consumer Key and Secret.

You'll need to get a hold of these yourself as I cannot provide them.

Regards,
Chris

**Comment by Tartoob** [comment]
I fetched Periscope Consumer Key and Secret, but is expired after 5 time of using it ):
I'll be glad to help you If you need any, but properly we should find pretty good solution for this issue

**Comment by cjhbtn** [comment]
Hi,

The Periscope OAuth Consumer and Secret do not expire - they are fixed values.

As mentioned, I cannot provide any details on obtaining these values, but they are available if you know where to look.

Regards,
Chris
